apiVersion: v1
kind: Pod
metadata:
  name: backend
  namespace: netpol-demo
  labels:
    app: backend   # <-- Added label to match Service
spec:
  containers:
    - name: backend
      image: docker.io/library/express:latest
      imagePullPolicy: IfNotPresent   # <-- Use local image
      ports:
      - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: netpol-demo
spec:
  selector:
    app: backend
  ports:
  - port: 3000
    targetPort: 3000
