apiVersion: v1
kind: Pod
metadata:
  name: resource-pod
  labels:
    app: resource-pod
    group: nginx
  namespace: test
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "10Mi"
        cpu: "1m"
      limits:
        memory: "10Mi"
        cpu: "1m"
